# Generated by Django 5.2.6 on 2025-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created_datetime',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='add_field',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cancelled_datetime',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cancelled_float',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='delete_field',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='edit_field',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_datetime',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
