# Generated by Django 5.2.6 on 2025-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatsheet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
