# Generated by Django 5.2.6 on 2025-09-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0002_alter_cheatsheet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='description',
        ),
    ]
