# Generated by Django 5.2.6 on 2025-09-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0003_remove_language_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheatsheet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='cheatsheet',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='cheatsheet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='cheat_sheet_id',
            new_name='cheat_sheet',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snippets', to='code_snippet.tag'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SnippetTag',
        ),
    ]
